version: "3.7"

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql

      
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes: 
      - type: bind
        source: ./Backend
        target: /app
      - type: bind
        source: ./Backend/node_modules
        target: /app/node_modules
    restart: unless-stopped
    environment:
      - DB_HOST=mysqldb
      - DB_USER=root
      - DB_PASSWORD=akash1743a
      - DB_NAME=ubereats
      - DB_PORT=3307
    networks: 
      - uber-eats

  # frontend:
  #   depends_on: 
  #     - backend
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   ports:
  #     - 3000:3000
  #   volumes: 
  #     - type: bind
  #       source: ./frontend
  #       target: /app
  #     - type: bind
  #       source: ./frontend/node_modules
  #       target: /app/node_modules
  #   restart: unless-stopped
  #   networks: 
  #     - uber-eats


networks: 
  uber-eats:

volumes: 
  db: